//Doctor Prescription constants
export const DOC_PRESCRIPTION_REQUEST = "DOC_PRESCRIPTION_REQUEST";
export const DOC_PRESCRIPTION_SUCCESS = "DOC_PRESCRIPTION_SUCCESS";
export const DOC_PRESCRIPTION_FAIL = "DOC_PRESCRIPTION_FAIL";

//Appointment Cancel constants
export const CANCEL_APPOINTMENT_REQUEST = "CANCEL_APPOINTMENT_REQUEST";
export const CANCEL_APPOINTMENT_SUCCESS = "CANCEL_APPOINTMENT_SUCCESS";
export const CANCEL_APPOINTMENT_FAIL = "CANCEL_APPOINTMENT_FAIL";

//Appointment Cancel constants
export const INCOMPLETE_APPOINTMENT_REQUEST = "INCOMPLETE_APPOINTMENT_REQUEST";
export const INCOMPLETE_APPOINTMENT_SUCCESS = "INCOMPLETE_APPOINTMENT_SUCCESS";
export const INCOMPLETE_APPOINTMENT_FAIL = "INCOMPLETE_APPOINTMENT_FAIL";

//Doc appointment list
export const DOC_APPOINTMENT_LIST_REQUEST = "DOC_APPOINTMENT_LIST_REQUEST";
export const DOC_APPOINTMENT_LIST_SUCCESS = "DOC_APPOINTMENT_LIST_SUCCESS";
export const DOC_APPOINTMENT_LIST_FAIL = "DOC_APPOINTMENT_LIST_FAIL";
export const DOC_APPOINTMENT_LIST_RESET = "DOC_APPOINTMENT_LIST_RESET";

//Patient appointment list
export const PAT_APPOINTMENT_LIST_REQUEST = "PAT_APPOINTMENT_LIST_REQUEST";
export const PAT_APPOINTMENT_LIST_SUCCESS = "PAT_APPOINTMENT_LIST_SUCCESS";
export const PAT_APPOINTMENT_LIST_FAIL = "PAT_APPOINTMENT_LIST_FAIL";

//appointment doctor constants
export const APPOINTMENTS_DOC_REQUEST = "APPOINTMENTS_DOC_REQUEST";
export const APPOINTMENTS_DOC_SUCCESS = "APPOINTMENTS_DOC_SUCCESS";
export const APPOINTMENTS_DOC_FAIL = "APPOINTMENTS_DOC_FAIL";

//appointment patient constants
export const APPOINTMENTS_PAT_REQUEST = "APPOINTMENTS_PAT_REQUEST";
export const APPOINTMENTS_PAT_SUCCESS = "APPOINTMENTS_PAT_SUCCESS";
export const APPOINTMENTS_PAT_FAIL = "APPOINTMENTS_PAT_FAIL";

//appointment form constants
export const APPOINTMENT_FORM_REQUEST = "APPOINTMENT_FORM_REQUEST";
export const APPOINTMENT_FORM_SUCCESS = "APPOINTMENT_FORM_SUCCESS";
export const APPOINTMENT_FORM_FAIL = "APPOINTMENT_FORM_FAIL";

//appointment doctor accept constants
export const DOC_APPOINTMENT_ACCEPT_REQUEST = "DOC_APPOINTMENT_ACCEPT_REQUEST";
export const DOC_APPOINTMENT_ACCEPT_SUCCESS = "DOC_APPOINTMENT_ACCEPT_SUCCESS";
export const DOC_APPOINTMENT_ACCEPT_FAIL = "DOC_APPOINTMENT_ACCEPT_FAIL";
