//Attendant constants
export const ATTENDANT_REQUEST = "ATTENDANT_REQUEST";
export const ATTENDANT_SUCCESS = "ATTENDANT_SUCCESS";
export const ATTENDANT_FAIL = "ATTENDANT_FAIL";

//Attendant constants
export const ATTENDANT_FORM_REQUEST = "ATTENDANT_FORM_REQUEST";
export const ATTENDANT_FORM_SUCCESS = "ATTENDANT_FORM_SUCCESS";
export const ATTENDANT_FORM_FAIL = "ATTENDANT_FORM_FAIL";
