// payment constants
export const PAYMENT_REQUEST = "PAYMENT_REQUEST";
export const PAYMENT_LOADING_SUCCESS = "PAYMENT_LOADING_SUCCESS";
export const PAYMENT_FAIL = "PAYMENT_FAIL";

export const CARD_DELETE_REQUEST = "CARD_DELETE_REQUEST";
export const CARD_DELETE_SUCCESS = "CARD_DELETE_SUCCESS";
export const CARD_DELETE_FAIL = "CARD_DELETE_FAIL";