// Pharmacy Form Constants
export const PHARMACY_FORM_REQUEST = "PHARMACY_FORM_REQUEST";
export const PHARMACY_FORM_SUCCESS = "PHARMACY_FORM_SUCCESS";
export const PHARMACY_FORM_FAIL = "PHARMACY_FORM_FAIL";

// Pharmacy Constants
export const PHARMACY_REQUEST = "PHARMACY_REQUEST";
export const PHARMACY_SUCCESS = "PHARMACY_SUCCESS";
export const PHARMACY_FAIL = "PHARMACY_FAIL";

// Pharmacy Constants
export const PHARMACY_DELETE_REQUEST = "PHARMACY_DELETE_REQUEST";
export const PHARMACY_DELETE_SUCCESS = "PHARMACY_DELETE_SUCCESS";
export const PHARMACY_DELETE_FAIL = "PHARMACY_DELETE_FAIL";