/**USER COSTANTS */

// user login constants
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

// user logout constant
export const USER_LOGOUT = "USER_LOGOUT";

// user register constants
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

// user details constant
export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

// user profile update constant
export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

// User Language Constants
export const LANGUAGE_USER_REQUEST = "LANGUAGE_USER_REQUEST";
export const LANGUAGE_USER_SUCCESS = "LANGUAGE_USER_SUCCESS";
export const LANGUAGE_USER_FAIL = "LANGUAGE_USER_FAIL";

// Pat appointment constants
export const APPOINTMENTS_PAT_REQUEST = "APPOINTMENTS_PAT_REQUEST";
export const APPOINTMENTS_PAT_SUCCESS = "APPOINTMENTS_PAT_SUCCESS";
export const APPOINTMENTS_PAT_FAIL = "APPOINTMENTS_PAT_FAIL";

// Doc appointment constants
export const APPOINTMENTS_DOC_REQUEST = "APPOINTMENTS_DOC_REQUEST";
export const APPOINTMENTS_DOC_SUCCESS = "APPOINTMENTS_DOC_SUCCESS";
export const APPOINTMENTS_DOC_FAIL = "APPOINTMENTS_DOC_FAIL";

export const TIMEZONE_REQUEST = "TIMEZONE_REQUEST";
export const TIMEZONE_SUCCESS = "TIMEZONE_SUCCESS";
export const TIMEZONE_FAIL = "TIMEZONE_FAIL";

// consult list for doctor Constants
export const SET_SOCKET = "SET_SOCKET";
export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";
export const CHAT_LIST_RESET = "CHAT_LIST_RESET";

// Chat Post Constants
export const CHAT_POST_REQUEST = "CHAT_POST_REQUEST";
export const CHAT_POST_SUCCESS = "CHAT_POST_SUCCESS";
export const CHAT_POST_FAIL = "CHAT_POST_FAIL";
export const CHAT_ADD = "CHAT_ADD";

// Doctor Age Group Select Constants
export const AGE_USER_REQUEST = "AGE_USER_REQUEST";
export const AGE_USER_SUCCESS = "AGE_USER_SUCCESS";
export const AGE_USER_FAIL = "AGE_USER_FAIL";

// Password Reset Constants
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";
export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_CONFIRM_FAIL = "PASSWORD_RESET_CONFIRM_FAIL";
export const PASSWORD_RESET_CONFIRM_SUCCESS = "PASSWORD_RESET_CONFIRM_SUCCESS";

export const ACTIVATE_FAIL = "ACTIVATE_FAIL";
export const ACTIVATE_SUCCESS = "ACTIVATE_SUCCESS";

export const LIST_ADD = "LIST_ADD";
export const RESET_MESSAGES = "RESET_MESSAGES";

// Notification
export const USER_NOTIFICATION_REQUEST = "USER_NOTIFICATION_REQUEST";
export const USER_NOTIFICATION_SUCCESS = "USER_NOTIFICATION_SUCCESS";
export const USER_NOTIFICATION_FAIL = "USER_NOTIFICATION_FAIL";
export const MESSAGE_COUNT = "MESSAGE_COUNT";

// Message Count Constants
export const PATIENT_MESSAGE_COUNT_SUCCESS = "PATIENT_MESSAGE_COUNT_SUCCESS";
export const DOCTOR_MESSAGE_COUNT_SUCCESS = "DOCTOR_MESSAGE_COUNT_SUCCESS";
export const MESSAGE_COUNT_SUCCESS = "MESSAGE_COUNT_SUCCESS";
export const MESSAGE_COUNT_FAIL = "MESSAGE_COUNT_FAIL";
export const MESSAGE_COUNT_REQUEST = "MESSAGE_COUNT_REQUEST";

// Appointment Handling by Doctor Request:
export const APPOINTMENT_FORM_REQUEST = "APPOINTMENT_FORM_REQUEST";
export const APPOINTMENT_FORM_SUCCESS = "APPOINTMENT_FORM_SUCCESS";
export const APPOINTMENT_FORM_FAIL = "APPOINTMENT_FORM_FAIL";

export const RESET_NOTIFICATION = "NOTIFICATION_ADD";

// COUNT NOTIFICATION
export const USER_NOTIFICATION_COUNT_REQUEST =
  "USER_NOTIFICATION_COUNT_REQUEST";
export const USER_NOTIFICATION_COUNT_SUCCESS =
  "USER_NOTIFICATION_COUNT_SUCCESS";
export const USER_NOTIFICATION_COUNT_FAIL = "USER_NOTIFICATION_COUNT_FAIL";

export const TREATMENTAREA_REQUEST = "TREATMENTAREA_REQUEST";
export const TREATMENTAREA_SUCCESS = "TREATMENTAREA_SUCCESS";
export const TREATMENTAREA_FAIL = "TREATMENTAREA_FAIL";
